INSERT INTO SubType (setID,cardID,subtype)
VALUES
('DEP','025','Aquatic'),
('DEP','049','Aquatic'),
('DEP','103','Aquatic'),
('QIL','108','Aquatic'),
('DEP','028','Aquatic, Beast'),
('DEP','031','Aquatic, Beast, Cephalopod'),
('DEP','065','Aquatic, Beast, Cephalopod'),
('DEP','012','Aquatic, Beast, Cetacean'),
('QIL','034','Aquatic, Beast, Cetacean'),
('DEP','030','Aquatic, Beast, Cetacean, Giant'),
('CLA','030','Aquatic, Beast, Human, Cleric'),
('DEP','069','Aquatic, Crab'),
('DEP','107','Aquatic, Crab'),
('QIL','106','Aquatic, Crab'),
('QIL','033','Aquatic, Crab, Cephalopod'),
('QIL','013','Aquatic, Crustacean'),
('QIL','066','Aquatic, Devil, Fish'),
('QIL','035','Aquatic, Dragon'),
('QIL','055','Aquatic, Dragon'),
('KGD','049','Aquatic, Dragon'),
('KGD','032','Aquatic, Dragon, Beast, Turtle'),
('DEP','090','Aquatic, Eldritch'),
('DEP','105','Aquatic, Eldritch'),
('QIL','086','Aquatic, Eldritch'),
('DEP','089','Aquatic, Eldritch, Crab'),
('QIL','031','Aquatic, Fish'),
('QIL','112','Aquatic, Fish'),
('QIL','114','Aquatic, Fish'),
('DEP','092','Aquatic, Monster'),
('QIL','110','Aquatic, Monster'),
('QIL','116','Aquatic, Plant'),
('DEP','011','Aquatic, Plant, Beast'),
('QIL','027','Aquatic, Rock, Fish'),
('DEP','029','Aquatic, Rock, Monster'),
('DEP','027','Aquatic, Tentacle'),
('DEP','050','Aquatic, Vehicle'),
('DEP','023','Aquatic, Wall'),
('DEP','087','Aquatic, Wall'),
('COR','039','Arachnid'),
('FAL','141','Beast, Bear, Cultist'),
('NIN','030','Beast, Bear, Machine'),
('COR','015','Beast, Bird, Merchant'),
('FAL','126','Beast, Cat, Cleric'),
('NIN','104','Beast, Cat, Entertainer'),
('FAL','038','Beast, Cat, Merchant'),
('JGK','039','Beast, Cat, Noble'),
('COR','017','Beast, Cat, Officer'),
('NIN','009','Beast, Cat, Rogue'),
('NIN','101','Beast, Cat, Shark, Merchant'),
('FAL','092','Beast, Cat, Soldier'),
('COR','095','Beast, Cat, Wizard'),
('NIN','028','Beast, Cow, Golem'),
('FAL','060','Beast, Dog, Fighter'),
('CLA','007','Beast, Fighter'),
('COR','099','Beast, Fox, Entertainer'),
('FAL','098','Beast, Fox, Entertainer'),
('NIN','026','Beast, Fox, Plant, Samurai'),
('NIN','098','Beast, Fox, Undead, Spirit'),
('NIN','056','Beast, Lizard, Fighter'),
('CLA','006','Beast, Merchant'),
('FAL','159','Beast, Rat, Entertainer'),
('COR','014','Beast, Rat, Rogue'),
('NIN','099','Beast, Rat, Samurai'),
('FAL','034','Beast, Rat, Swarm'),
('KGD','027','Beast, Rodent'),
('KGD','041','Beast, Rodent'),
('FAL','107','Beast, Rodent, Engineer'),
('FAL','165','Beast, Rodent, Entertainer'),
('NIN','035','Beast, Rodent, Knight'),
('NIN','024','Beast, Rodent, Noble'),
('CLA','005','Beast, Rogue'),
('COR','101','Beast, Shark, Human'),
('NIN','076','Beast, Shark, Noble'),
('COR','122','Beast, Sheep'),
('COR','042','Beast, Sheep, Merchant'),
('NIN','074','Beast, Snake'),
('KGD','073','Beast, Snake, Cultist'),
('FAL','104','Beast, Snake, Knight'),
('NIN','079','Beast, Snake, Wizard'),
('KGD','031','Beast, Wolf, Cultist'),
('WHV','030','Beholder'),
('KGD','069','Bird'),
('JGK','028','Bird'),
('FAL','102','Bird, Clock, Soldier'),
('JGK','027','Bird, Demon'),
('CLA','043','Bird, Human, Cleric'),
('FAL','168','Bird, Merchant'),
('NIN','027','Bird, Noble'),
('NIN','054','Bird, Officer'),
('COR','067','Bird, Rogue'),
('FAL','163','Bird, Rogue'),
('COR','097','Bird, Wizard'),
('NIN','036','Celestial'),
('COR','023','Celestial, Beast, Dog'),
('FAL','101','Celestial, Beast, Rodent, Vehicle'),
('KGD','048','Celestial, Dragon'),
('FAL','143','Celestial, Dragon'),
('COR','125','Celestial, Eldritch, Insect'),
('FAL','042','Celestial, Elemental'),
('FAL','109','Celestial, Entertainer'),
('FAL','049','Celestial, Giant'),
('COR','096','Celestial, Knight'),
('FAL','140','Celestial, Knight'),
('FAL','110','Celestial, Machine, Mech'),
('NIN','048','Celestial, Officer'),
('FAL','134','Celestial, Official'),
('FAL','144','Celestial, Rock, Elemental'),
('FAL','125','Celestial, Rogue'),
('FAL','136','Celestial, Slime'),
('FAL','164','Celestial, Slime'),
('COR','098','Celestial, Spirit'),
('COR','128','Celestial, Spirit, Beast, Cetacean'),
('NIN','061','Celestial, Vehicle'),
('FAL','199','Celestial, Vehicle, Entertainer'),
('FAL','059','Celestial, Worker'),
('FAL','096','Celestial, Worker'),
('COR','124','Cephalopod, Cultist'),
('FAL','094','Civilian'),
('FAL','072','Clock, Golem, Noble, Warrior'),
('FAL','097','Clock, Machine, Fighter'),
('FAL','108','Clock, Machine, Official'),
('FAL','027','Clock, Machine, Soldier'),
('FAL','068','Clock, Rock, Elemental'),
('HOE','004','Concept'),
('HOE','090','Concept'),
('HOE','091','Concept'),
('HOE','092','Concept'),
('HOE','093','Concept'),
('HOE','094','Concept'),
('HOE','095','Concept'),
('HOE','096','Concept'),
('HOE','097','Concept'),
('HOE','098','Concept'),
('HOE','099','Concept'),
('COR','056','Consumable'),
('COR','057','Consumable'),
('COR','059','Consumable'),
('COR','083','Consumable'),
('COR','112','Consumable'),
('COR','140','Consumable'),
('KGD','039','Consumable'),
('KGD','053','Consumable'),
('KGD','067','Consumable'),
('KGD','081','Consumable'),
('NIN','043','Consumable'),
('JGK','049','Consumable'),
('FAL','088','Consumable'),
('HOE','001','Crab'),
('HOE','009','Crab'),
('HOE','010','Crab'),
('HOE','012','Crab'),
('HOE','016','Crab'),
('HOE','017','Crab'),
('HOE','018','Crab'),
('COR','040','Crab, Giant'),
('QIL','054','Crab, Monster'),
('JGK','013','Crab, Monster'),
('HOE','011','Crustacean'),
('HOE','013','Crustacean'),
('HOE','014','Crustacean'),
('HOE','015','Crustacean'),
('JGK','043','Deity'),
('FAL','145','Deity, Celestial, Snake'),
('JGK','042','Deity, Monster, Snake'),
('FAL','065','Demon, Beast'),
('JGK','030','Demon, Beast, Dog'),
('JGK','032','Demon, Beast, Dog'),
('JGK','041','Demon, Beast, Dog'),
('FAL','061','Demon, Beast, Dog, Fighter'),
('JGK','034','Demon, Beast, Dog, Monster'),
('FAL','070','Demon, Beast, Ranger'),
('NIN','108','Demon, Fighter'),
('JGK','012','Demon, Fighter'),
('FAL','158','Demon, Fighter'),
('FAL','175','Demon, Knight'),
('JGK','009','Demon, Ranger'),
('COR','022','Demon, Rock, Beast, Bird, Dog, Fighter'),
('NIN','125','Demon, Rogue, Fighter'),
('JGK','016','Demon, Soldier'),
('JGK','018','Demon, Soldier'),
('NIN','014','Demon, Worker'),
('HOE','002','Devil'),
('HOE','036','Devil'),
('HOE','037','Devil'),
('HOE','038','Devil'),
('HOE','039','Devil'),
('HOE','040','Devil'),
('HOE','041','Devil'),
('WHV','059','Devil'),
('WHV','058','Devil, Fighter'),
('KGD','009','Dragon'),
('KGD','012','Dragon'),
('KGD','014','Dragon'),
('KGD','016','Dragon'),
('KGD','017','Dragon'),
('KGD','028','Dragon'),
('KGD','030','Dragon'),
('KGD','033','Dragon'),
('KGD','035','Dragon'),
('KGD','036','Dragon'),
('KGD','042','Dragon'),
('KGD','044','Dragon'),
('KGD','047','Dragon'),
('KGD','050','Dragon'),
('KGD','056','Dragon'),
('KGD','058','Dragon'),
('KGD','061','Dragon'),
('KGD','063','Dragon'),
('KGD','064','Dragon'),
('KGD','070','Dragon'),
('KGD','072','Dragon'),
('KGD','075','Dragon'),
('KGD','077','Dragon'),
('KGD','078','Dragon'),
('KGD','008','Dragon, Cultist'),
('KGD','029','Dragon, Druid'),
('KGD','043','Dragon, Engineer'),
('NIN','011','Dragon, Fighter'),
('FAL','195','Dragon, Fighter, Rogue'),
('KGD','018','Dragon, Giant'),
('KGD','062','Dragon, Golem'),
('KGD','046','Dragon, Machine, Mech'),
('WHV','074','Dragon, Merchant'),
('NIN','031','Dragon, Monk'),
('FAL','073','Dragon, Monk'),
('KGD','071','Dragon, Rogue'),
('QIL','072','Dragon, Spirit'),
('KGD','010','Dragon, Wizard'),
('KGD','057','Dragon, Wizard'),
('NIN','052','Drone'),
('NIN','057','Drone'),
('KGD','045','Dwarf, Cultist'),
('WHV','031','Dwarf, Fighter'),
('COR','103','Earth'),
('FAL','079','Earth'),
('FAL','117','Earth'),
('FAL','154','Earth, Rock, Weapon'),
('KGD','006','Egg'),
('FAL','174','Eldritch, Arachnid'),
('QIL','095','Eldritch, Beast'),
('FAL','161','Eldritch, Beast'),
('FAL','046','Eldritch, Beast, Horse'),
('FAL','142','Eldritch, Celestial'),
('FAL','167','Eldritch, Cephalopod, Cultist'),
('NIN','128','Eldritch, Cleric, Cultist'),
('FAL','138','Eldritch, Crab, Cultist'),
('COR','123','Eldritch, Cultist'),
('NIN','100','Eldritch, Cultist'),
('FAL','173','Eldritch, Cultist, Knight'),
('COR','132','Eldritch, Deity'),
('FAL','177','Eldritch, Deity'),
('KGD','076','Eldritch, Dragon'),
('FAL','169','Eldritch, Elemental'),
('FAL','162','Eldritch, Insect'),
('NIN','077','Eldritch, Knight, Cultist'),
('COR','131','Eldritch, Monster'),
('JGK','038','Eldritch, Monster'),
('COR','127','Eldritch, Spirit'),
('FAL','201','Eldritch, Spirit'),
('FAL','160','Eldritch, Tentacle'),
('NIN','075','Eldritch, Wizard'),
('COR','048','Elemental'),
('QIL','068','Elemental'),
('JGK','040','Elemental'),
('QIL','049','Elemental, Machine'),
('COR','045','Elemental, Spirit'),
('QIL','026','Elemental, Spirit'),
('WHV','046','Elf, Arachnid, Merchant'),
('FAL','129','Elf, Cleric'),
('FAL','135','Elf, Cleric'),
('FAL','127','Elf, Cultist'),
('WHV','029','Elf, Druid'),
('NIN','029','Elf, Druid'),
('FAL','062','Elf, Druid'),
('FAL','063','Elf, Druid'),
('COR','041','Elf, Druid, Fighter'),
('COR','046','Elf, Druid, Rogue'),
('FAL','064','Elf, Entertainer'),
('FAL','067','Elf, Knight'),
('FAL','193','Elf, Merchant, Wizard'),
('FAL','036','Elf, Noble, Merchant'),
('FAL','069','Elf, Official'),
('FAL','132','Elf, Official'),
('WHV','044','Elf, Pirate'),
('QIL','046','Elf, Pirate'),
('WHV','042','Elf, Pirate, Worker'),
('FAL','130','Elf, Ranger, Wizard'),
('NIN','080','Elf, Wizard'),
('FAL','028','Elf, Wizard'),
('KGD','060','Fey, Dragon'),
('FAL','066','Fey, Elemental'),
('FAL','128','Fey, Elf, Maid, Entertainer'),
('QIL','047','Fey, Pirate'),
('COR','054','Fire'),
('COR','106','Fire'),
('QIL','041','Fire'),
('FAL','075','Fire'),
('JGK','052','Fire, Ice'),
('WHV','063','Fire, Shadow'),
('FAL','031','Fish, Worker'),
('COR','031','Gear'),
('COR','080','Gear'),
('COR','143','Gear'),
('NIN','045','Gear'),
('NIN','067','Gear'),
('NIN','094','Gear'),
('JGK','023','Gear'),
('FAL','119','Gear'),
('FAL','198','Gear'),
('FAL','200','Gear'),
('KGD','055','Goblin'),
('WHV','028','Goblin, Fighter'),
('QIL','015','Golem, Engineer'),
('NIN','049','Golem, Officer'),
('FAL','044','Golem, Scientist'),
('COR','107','Holy'),
('WHV','060','Holy'),
('DEP','076','Holy'),
('QIL','042','Holy'),
('QIL','077','Holy'),
('QIL','078','Holy'),
('QIL','082','Holy'),
('CLA','046','Holy'),
('CLA','047','Holy'),
('CLA','048','Holy'),
('FAL','150','Holy'),
('FAL','120','Holy, Consumable'),
('HOE','003','Human'),
('HOE','063','Human'),
('HOE','064','Human'),
('HOE','065','Human'),
('HOE','066','Human'),
('HOE','067','Human'),
('HOE','068','Human'),
('HOE','069','Human'),
('DEP','091','Human'),
('NIN','073','Human, Agent'),
('WHV','013','Human, Bird, Soldier'),
('KGD','007','Human, Cavalry'),
('COR','129','Human, Cultist'),
('WHV','057','Human, Cultist'),
('DEP','085','Human, Cultist'),
('NIN','102','Human, Cultist'),
('COR','069','Human, Engineer'),
('QIL','051','Human, Engineer'),
('FAL','095','Human, Engineer'),
('FAL','099','Human, Engineer'),
('FAL','039','Human, Entertainer'),
('FAL','170','Human, Entertainer'),
('COR','019','Human, Fighter'),
('COR','044','Human, Fighter'),
('DEP','044','Human, Fighter'),
('DEP','106','Human, Fighter'),
('KGD','015','Human, Fighter'),
('WHV','075','Human, Fighter, Rogue'),
('FAL','100','Human, Maid, Entertainer'),
('COR','016','Human, Merchant'),
('WHV','015','Human, Merchant'),
('DEP','088','Human, Merchant'),
('QIL','048','Human, Merchant'),
('NIN','107','Human, Merchant'),
('NIN','127','Human, Merchant'),
('DEP','086','Human, Merchant, Rogue'),
('NIN','081','Human, Noble'),
('KGD','059','Human, Noble, Cultist'),
('NIN','124','Human, Noble, Knight'),
('NIN','012','Human, Officer'),
('NIN','060','Human, Officer'),
('FAL','033','Human, Officer'),
('COR','126','Human, Official'),
('FAL','172','Human, Official'),
('QIL','092','Human, Pirate'),
('DEP','084','Human, Pirate, Cultist'),
('DEP','108','Human, Pirate, Rogue'),
('QIL','087','Human, Pirate, Wizard'),
('COR','100','Human, Priest'),
('COR','070','Human, Rogue'),
('WHV','071','Human, Rogue'),
('WHV','073','Human, Rogue'),
('DEP','043','Human, Scientist'),
('DEP','045','Human, Scientist'),
('QIL','050','Human, Scientist'),
('COR','020','Human, Soldier'),
('WHV','012','Human, Soldier'),
('DEP','013','Human, Soldier'),
('FAL','133','Human, Wizard, Merchant'),
('COR','109','Ice'),
('COR','110','Ice'),
('WHV','078','Ice'),
('FAL','147','Ice'),
('QIL','074','Illithid, Deity'),
('QIL','071','Illithid, Monster'),
('QIL','069','Illithid, Pilot'),
('JGK','033','Insect'),
('NIN','055','Insect, Drone'),
('FAL','137','Insect, Scientist'),
('CLA','032','Legendary'),
('CLA','064','Legendary'),
('KGD','022','Legendary'),
('KGD','026','Legendary'),
('QIL','001','Legendary, Aquatic, Golem, Official'),
('NIN','005','Legendary, Beast, Alligator, Agent'),
('FAL','025','Legendary, Beast, Alligator, Hero'),
('NIN','003','Legendary, Beast, Cat, Noble'),
('NIN','002','Legendary, Beast, Cat, Officer'),
('NIN','001','Legendary, Beast, Cat, Official'),
('FAL','002','Legendary, Beast, Fox, Entertainer'),
('COR','010','Legendary, Beast, Nightmare'),
('FAL','013','Legendary, Beast, Plant, Druid, Deity'),
('FAL','016','Legendary, Beast, Rat, Spirit'),
('FAL','009','Legendary, Beast, Shark, Fighter'),
('NIN','006','Legendary, Beast, Sheep, Merchant'),
('FAL','015','Legendary, Bird, Human, Civilian'),
('CLA','003','Legendary, Bird, Human, Cleric'),
('FAL','007','Legendary, Bird, Knight, Hero'),
('FAL','012','Legendary, Celestial, Cleric'),
('FAL','011','Legendary, Celestial, Demon, Spirit'),
('FAL','014','Legendary, Clock, Human, Deity'),
('HOE','089','Legendary, Concept'),
('COR','001','Legendary, Demon, Beast'),
('FAL','020','Legendary, Demon, Beast, Dog, Fighter'),
('FAL','019','Legendary, Demon, Bird, Entertainer'),
('FAL','005','Legendary, Demon, Villain'),
('HOE','035','Legendary, Devil'),
('KGD','005','Legendary, Dragon'),
('KGD','003','Legendary, Dragon, Deity'),
('KGD','001','Legendary, Dragon, Human, Knight'),
('KGD','002','Legendary, Dragon, Monster'),
('KGD','004','Legendary, Dragon, Wizard'),
('WHV','003','Legendary, Dwarf, Cleric'),
('QIL','003','Legendary, Dwarf, Cleric, Engineer'),
('COR','011','Legendary, Eldritch, Beast, Goat, Druid'),
('COR','005','Legendary, Eldritch, Fighter'),
('FAL','008','Legendary, Eldritch, Human, Cleric'),
('FAL','017','Legendary, Eldritch, Human, Cultist'),
('NIN','007','Legendary, Eldritch, Villain'),
('FAL','026','Legendary, Eldritch, Villain'),
('WHV','005','Legendary, Elf, Agent'),
('QIL','002','Legendary, Elf, Agent, Druid'),
('WHV','009','Legendary, Elf, Fighter'),
('FAL','022','Legendary, Elf, Noble, Official'),
('WHV','006','Legendary, Elf, Pirate, Rogue, Villain'),
('WHV','001','Legendary, Elf, Rogue'),
('WHV','010','Legendary, Elf, Scientist, Villain'),
('QIL','004','Legendary, Elf, Vampire, Fighter'),
('COR','009','Legendary, Fey, Wizard'),
('HOE','062','Legendary, Human'),
('FAL','010','Legendary, Human, Agent, Swarm'),
('FAL','024','Legendary, Human, Celestial, Scientist'),
('DEP','009','Legendary, Human, Cultist, Pirate'),
('QIL','006','Legendary, Human, Engineer'),
('COR','007','Legendary, Human, Engineer, Official'),
('FAL','004','Legendary, Human, Entertainer'),
('WHV','002','Legendary, Human, Fighter'),
('WHV','004','Legendary, Human, Fighter, Villain'),
('FAL','001','Legendary, Human, Hero'),
('COR','008','Legendary, Human, Maid, Knight'),
('DEP','001','Legendary, Human, Merchant'),
('WHV','008','Legendary, Human, Noble, Cultist, Villain'),
('QIL','008','Legendary, Human, Pirate'),
('QIL','010','Legendary, Human, Pirate, Noble'),
('DEP','005','Legendary, Human, Pirate, Rogue'),
('DEP','008','Legendary, Human, Rogue, Scientist'),
('NIN','004','Legendary, Human, Samurai'),
('DEP','003','Legendary, Human, Scientist'),
('FAL','021','Legendary, Machine, Deity'),
('COR','006','Legendary, Machine, Scientist'),
('COR','004','Legendary, Plant, Wizard'),
('QIL','009','Legendary, Qil''oth, Agent'),
('QIL','012','Legendary, Qil''oth, Deity'),
('DEP','007','Legendary, QIl''oth, Fighter'),
('DEP','006','Legendary, Qil''oth, Merchant'),
('DEP','002','Legendary, Qil''oth, Ranger'),
('QIL','007','Legendary, Qil''oth, Ranger'),
('DEP','004','Legendary, Qil''oth, Wizard'),
('FAL','003','Legendary, Rock, Human, Gamer'),
('FAL','018','Legendary, Rock, Spirit'),
('CLA','004','Legendary, Seaborn, Aquatic, Monster'),
('CLA','002','Legendary, Seaborn, Aquatic, Monster, Human, Agent'),
('CLA','001','Legendary, Seaborn, Aquatic, Monster, Human, Entertainer'),
('FAL','006','Legendary, Spirit, Skeleton, Entertainer'),
('WHV','007','Legendary, Tiefling, Cleric'),
('QIL','005','Legendary, Tiefling, Undead, Villain'),
('JGK','001','Legendary, Undead, Pirate'),
('QIL','011','Legendary, Undead, Qil''oth, Wizard'),
('COR','003','Legendary, Undead, Skeleton, Merchant, Priest'),
('COR','002','Legendary, Undead, Spirit, Maid'),
('JGK','002','Legendary, Vampire, Criminal'),
('FAL','023','Legendary, Vampire, Entertainer'),
('COR','105','Lightning'),
('WHV','064','Lightning'),
('KGD','065','Lightning'),
('NIN','090','Lightning'),
('FAL','151','Lightning'),
('COR','068','Machine'),
('DEP','046','Machine'),
('DEP','051','Machine'),
('QIL','052','Machine'),
('NIN','053','Machine'),
('FAL','197','Machine'),
('NIN','050','Machine, Agent'),
('DEP','047','Machine, Crab'),
('FAL','043','Machine, Hero, Knight'),
('NIN','058','Machine, Mech'),
('FAL','103','Machine, Mech, Dwarf, Worker'),
('WHV','043','Machine, Merchant'),
('DEP','048','Machine, Shark'),
('COR','071','Machine, Spirit'),
('FAL','045','Machine, Spirit'),
('FAL','105','Machine, Spirit, Entertainer'),
('COR','066','Machine, Swarm'),
('COR','021','Machine, Vehicle'),
('COR','072','Machine, Vehicle'),
('COR','073','Machine, Vehicle'),
('COR','074','Machine, Vehicle'),
('QIL','016','Machine, Vehicle'),
('NIN','010','Machine, Wizard'),
('COR','094','Mana, Bird'),
('NIN','123','Mech, Officer'),
('CLA','031','Merchant'),
('NIN','032','Monster'),
('NIN','059','Monster'),
('NIN','082','Monster'),
('NIN','105','Monster, Fighter'),
('NIN','013','Monster, Merchant'),
('COR','049','Nature'),
('COR','053','Nature'),
('WHV','034','Nature'),
('WHV','037','Nature'),
('QIL','039','Nature'),
('FAL','078','Nature'),
('FAL','084','Nature'),
('FAL','086','Nature'),
('NIN','106','Nightmare'),
('KGD','011','Nightmare, Dragon'),
('COR','012','Nightmare, Merchant'),
('DEP','083','Nightmare, Spirit'),
('NIN','111','Nightmare, Spirit'),
('NIN','033','Officer, Vehicle'),
('WHV','033','Orc, Fighter'),
('QIL','053','Pirate, Vehicle, Swarm'),
('COR','043','Plant'),
('COR','047','Plant, Beast, Dinosaur'),
('FAL','032','Plant, Cultist'),
('KGD','034','Plant, Dragon'),
('COR','038','Plant, Druid'),
('FAL','071','Plant, Druid'),
('WHV','032','Plant, Elemental, Spirit'),
('FAL','041','Plant, Entertainer'),
('FAL','074','Plant, Golem'),
('QIL','028','Plant, Knight'),
('NIN','023','Plant, Machine, Officer'),
('QIL','094','Plant, Vehicle, Swarm'),
('QIL','067','Qil''oth, Agent'),
('NIN','078','Qil''oth, Agent'),
('DEP','024','Qil''oth, Civilian'),
('DEP','068','Qil''oth, Druid'),
('DEP','071','Qil''oth, Druid'),
('DEP','014','Qil''oth, Entertainer'),
('DEP','026','Qil''oth, Fighter'),
('DEP','067','Qil''oth, Knight'),
('QIL','029','Qil''oth, Knight'),
('QIL','090','Qil''oth, Undead, Zombie'),
('WHV','072','Rat, Rogue'),
('FAL','030','Rock'),
('FAL','124','Rock'),
('FAL','153','Rock'),
('FAL','156','Rock'),
('DEP','066','Rock, Crab'),
('KGD','013','Rock, Dragon'),
('FAL','093','Rock, Dwarf, Merchant'),
('ELM','006','Rock, Elemental'),
('FAL','191','Rock, Elemental'),
('JGK','035','Rock, Entertainer'),
('NIN','034','Rock, Fighter'),
('FAL','121','Rock, Gear'),
('FAL','047','Rock, Golem'),
('FAL','106','Rock, Golem'),
('FAL','131','Rock, Golem'),
('NIN','025','Rogue, Merchant'),
('HOE','005','Sand, Castle'),
('CLA','015','Seaborn, Aquatic, Monster'),
('CLA','017','Seaborn, Aquatic, Monster'),
('CLA','018','Seaborn, Aquatic, Monster'),
('CLA','019','Seaborn, Aquatic, Monster'),
('CLA','020','Seaborn, Aquatic, Monster'),
('CLA','021','Seaborn, Aquatic, Monster'),
('CLA','022','Seaborn, Aquatic, Monster'),
('CLA','023','Seaborn, Aquatic, Monster'),
('CLA','057','Seaborn, Aquatic, Monster'),
('CLA','058','Seaborn, Aquatic, Monster'),
('CLA','059','Seaborn, Aquatic, Monster'),
('CLA','062','Seaborn, Aquatic, Monster'),
('CLA','063','Seaborn, Aquatic, Monster'),
('CLA','024','Seaborn, Aquatic, Monster, Beast, Knight'),
('CLA','061','Seaborn, Aquatic, Monster, Cleric'),
('CLA','060','Seaborn, Aquatic, Monster, Entertainer'),
('CLA','029','Seaborn, Aquatic, Monster, Human, Agent'),
('CLA','016','Seaborn, Aquatic, Monster, Human, Ranger'),
('COR','133','Shadow'),
('COR','136','Shadow'),
('COR','137','Shadow'),
('DEP','072','Shadow'),
('QIL','076','Shadow'),
('QIL','098','Shadow'),
('NIN','037','Shadow'),
('NIN','088','Shadow'),
('NIN','091','Shadow'),
('NIN','113','Shadow'),
('JGK','022','Shadow'),
('FAL','090','Shadow'),
('FAL','178','Shadow'),
('FAL','182','Shadow'),
('FAL','187','Shadow'),
('FAL','190','Shadow'),
('FAL','202','Shadow'),
('NIN','109','Slime, Monster'),
('COR','018','Spirit'),
('FAL','166','Spirit'),
('QIL','032','Spirit, Beast, Shark'),
('QIL','030','Spirit, Bird'),
('FAL','139','Spirit, Celestial'),
('DEP','104','Spirit, Giant, Beast, Cetacean'),
('NIN','051','Spirit, Machine'),
('QIL','073','Spirit, Nightmare'),
('DEP','063','Spirit, Qil''oth'),
('DEP','064','Spirit, Qil''oth'),
('DEP','070','Spirit, Qil''oth'),
('QIL','070','Spirit, Qil''oth'),
('JGK','036','Spirit, Skeleton, Cavalry'),
('JGK','015','Spirit, Skeleton, Engineer'),
('JGK','008','Spirit, Skeleton, Ranger'),
('WHV','056','Tiefling, Cultist'),
('WHV','014','Tiefling, Merchant'),
('COR','T06','Token'),
('HOE','019','Token'),
('HOE','070','Token'),
('HOE','100','Token'),
('HOE','101','Token'),
('ELM','027','Token'),
('WHV','T03','Token'),
('QIL','T02','Token'),
('QIL','T05','Token'),
('QIL','T07','Token'),
('CLA','T01','Token'),
('CLA','T04','Token'),
('CLA','T05','Token'),
('NIN','T01','Token'),
('NIN','T02','Token'),
('JGK','T01','Token'),
('FAL','T01','Token'),
('FAL','T05','Token'),
('FAL','T10','Token'),
('DEP','T02','Token, Aquatic, Beast, Cephalopod'),
('DEP','T01','Token, Aquatic, Tentacle'),
('FAL','T13','Token, Beast, Civilian'),
('COR','T11','Token, Beast, Shark, Human'),
('COR','T03','Token, Crab, Giant'),
('JGK','T02','Token, Crab, Giant'),
('JGK','T04','Token, Demon, Beast, Dog'),
('JGK','T05','Token, Demon, Beast, Dog'),
('FAL','T03','Token, Demon, Beast, Dog, Fighter'),
('FAL','T04','Token, Demon, Beast, Dog, Fighter'),
('WHV','T04','Token, Devil'),
('ELM','011','Token, Earth, Elemental'),
('FAL','T11','Token, Eldritch, Elemental'),
('COR','T12','Token, Eldritch, Monster'),
('COR','T09','Token, Elemental'),
('COR','T08','Token, Elemental, Rock, Golem'),
('FAL','T08','Token, Elemental, Rock, Golem'),
('COR','T07','Token, Elemental, Wall'),
('FAL','T07','Token, Elemental, Wall'),
('WHV','T02','Token, Elf, Pirate'),
('WHV','T01','Token, Goblin, Fighter'),
('QIL','T01','Token, Golem'),
('FAL','T12','Token, Human, Civilian'),
('FAL','T09','Token, Human, Civilian, Swarm'),
('NIN','T03','Token, Human, Noble, Knight'),
('WHV','T07','Token, Human, Rogue'),
('KGD','T01','Token, Lightning'),
('COR','T04','Token, Machine, Beast, Cat'),
('COR','T05','Token, Machine, Human, Soldier'),
('QIL','T04','Token, Machine, Vehicle, Crab'),
('COR','T10','Token, Mana, Shapeshifter'),
('COR','T01','Token, Plant'),
('WHV','T06','Token, Plant, Undead, Zombie'),
('CLA','T02','Token, Seaborn, Aquatic, Monster'),
('CLA','T03','Token, Seaborn, Aquatic, Monster'),
('CLA','T06','Token, Seaborn, Aquatic, Monster'),
('QIL','T03','Token, Spirit, Beast'),
('WHV','T05','Token, Tiefling, Cultist'),
('FAL','T06','Token, Undead'),
('JGK','T03','Token, Undead, Bird'),
('FAL','T02','Token, Undead, Bird'),
('COR','T02','Token, Undead, Maid'),
('QIL','T06','Token, Undead, Zombie, Plant'),
('WHV','T09','Transformed'),
('WHV','T08','Transformed, Legendary, Dwarf, Cleric, Merchant'),
('WHV','T10','Transformed, Legendary, Elf, Agent, Druid'),
('WHV','T14','Transformed, Legendary, Elf, Vampire, Fighter'),
('WHV','T12','Transformed, Legendary, Tiefling, Undead, Cleric'),
('WHV','T11','Transformed, Machine, Orb'),
('WHV','T13','Transformed, Shadow'),
('WHV','T15','Transformed, Undead, Zombie'),
('NIN','084','Undead'),
('JGK','037','Undead'),
('JGK','031','Undead, Beast, Sheep'),
('JGK','029','Undead, Bird'),
('WHV','070','Undead, Bird, Merchant'),
('FAL','171','Undead, Deity'),
('KGD','074','Undead, Dragon, Slime'),
('DEP','010','Undead, Plant, Crab'),
('FAL','029','Undead, Skeleton, Demon'),
('QIL','093','Undead, Skeleton, Dragon'),
('JGK','020','Undead, Skeleton, Golem'),
('JGK','019','Undead, Skeleton, Noble'),
('FAL','040','Undead, Skeleton, Noble'),
('COR','013','Undead, Skeleton, Ranger'),
('NIN','008','Undead, Skeleton, Rogue'),
('JGK','010','Undead, Spirit'),
('JGK','014','Undead, Spirit'),
('FAL','048','Undead, Spirit'),
('NIN','126','Undead, Spirit, Agent'),
('FAL','037','Undead, Spirit, Agent'),
('WHV','011','Undead, Spirit, Merchant'),
('QIL','088','Undead, Zombie'),
('JGK','011','Undead, Zombie'),
('JGK','017','Undead, Zombie, Criminal'),
('WHV','076','Undead, Zombie, Giant'),
('NIN','083','Undead, Zombie, Noble, Soldier'),
('QIL','089','Undead, Zombie, Pirate'),
('QIL','091','Undead, Zombie, Plant'),
('QIL','014','Undead, Zombie, Worker'),
('FAL','035','Vampire, Fighter'),
('COR','130','Vampire, Rogue'),
('FAL','176','Vampire, Rogue, Spirit'),
('NIN','110','Vampire, Samurai, Rogue'),
('NIN','103','Vampire, Wizard'),
('WHV','045','Vehicle'),
('ELM','025','Water, Elemental, Abomination'),
('COR','032','Weapon'),
('COR','060','Weapon'),
('COR','116','Weapon'),
('COR','139','Weapon'),
('NIN','044','Weapon'),
('NIN','047','Weapon'),
('NIN','071','Weapon'),
('NIN','072','Weapon'),
('NIN','118','Weapon'),
('NIN','120','Weapon'),
('NIN','122','Weapon'),
('JGK','050','Weapon'),
('FAL','087','Weapon'),
('FAL','091','Weapon'),
('FAL','192','Weapon');
